
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wopr-model-webui"
version = "0.1.6-beta"
description = "WOPR - Model Control"
authors = [{ name = "Bob Bomar", email = "bob@bomar.us" }]
dependencies = [
    "streamlit",
    "httpx",
    "requests",
    "pydantic",
    "pylint",
    "label_studio_sdk",
]

[project.optional-dependencies]
dev = [
  "black",
  "django-stubs",
  "ipdb",
  "pip-tools",
  "ruff",
  "pytest",
  ]
