# Generated by Django 5.1.15 on 2026-01-29 02:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelFamily",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("shortname", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Model Families",
                "db_table": "model_families",
                "indexes": [
                    models.Index(fields=["uuid"], name="model_famil_uuid_c85164_idx"),
                    models.Index(fields=["name"], name="model_famil_name_2a919e_idx"),
                    models.Index(
                        fields=["shortname"], name="model_famil_shortna_39d2a9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="model_famil_created_d8c33e_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="model_famil_updated_0c2f62_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("shortname", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="core.modelfamily",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model Info",
                "db_table": "model_info",
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("version", models.IntegerField()),
                ("artifact_uri", models.CharField(max_length=1024, unique=True)),
                ("checksum", models.CharField(blank=True, max_length=128, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.modelinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model Versions",
                "db_table": "model_version",
            },
        ),
        migrations.CreateModel(
            name="ModelStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("observed_at", models.DateTimeField()),
                ("has_distfile", models.BooleanField(default=False)),
                ("has_backup", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_observations",
                        to="core.modelversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model Statuses",
                "db_table": "model_status",
            },
        ),
        migrations.CreateModel(
            name="ModelBackup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("taken_at", models.DateTimeField()),
                ("was_successful", models.BooleanField(default=False)),
                ("artifact_uri", models.CharField(max_length=1024, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="core.modelversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model Backups",
                "db_table": "model_backup",
            },
        ),
        migrations.AddIndex(
            model_name="modelinfo",
            index=models.Index(fields=["uuid"], name="model_info_uuid_8db5c2_idx"),
        ),
        migrations.AddIndex(
            model_name="modelinfo",
            index=models.Index(fields=["name"], name="model_info_name_e2ff4a_idx"),
        ),
        migrations.AddIndex(
            model_name="modelinfo",
            index=models.Index(
                fields=["shortname"], name="model_info_shortna_b54f6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelinfo",
            index=models.Index(
                fields=["created_at"], name="model_info_created_763f7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelinfo",
            index=models.Index(
                fields=["updated_at"], name="model_info_updated_4ecf4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(fields=["uuid"], name="model_versi_uuid_48e2ab_idx"),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["version"], name="model_versi_version_5813e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["is_current"], name="model_versi_is_curr_44188e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["created_at"], name="model_versi_created_aa9a6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["updated_at"], name="model_versi_updated_55b85e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelstatus",
            index=models.Index(fields=["uuid"], name="model_statu_uuid_4b281a_idx"),
        ),
        migrations.AddIndex(
            model_name="modelstatus",
            index=models.Index(
                fields=["observed_at"], name="model_statu_observe_e7bfa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelstatus",
            index=models.Index(
                fields=["created_at"], name="model_statu_created_c66619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelstatus",
            index=models.Index(
                fields=["updated_at"], name="model_statu_updated_b7bce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelbackup",
            index=models.Index(fields=["uuid"], name="model_backu_uuid_17ee48_idx"),
        ),
        migrations.AddIndex(
            model_name="modelbackup",
            index=models.Index(
                fields=["taken_at"], name="model_backu_taken_a_e619da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelbackup",
            index=models.Index(
                fields=["was_successful"], name="model_backu_was_suc_2e9245_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelbackup",
            index=models.Index(
                fields=["created_at"], name="model_backu_created_4c95e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelbackup",
            index=models.Index(
                fields=["updated_at"], name="model_backu_updated_80676f_idx"
            ),
        ),
    ]
