# Generated by Django 5.1.15 on 2026-01-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_modelfamily_mf_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelbackup",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="modelfamily",
            name="mf_status",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="artifact_uri",
            field=models.CharField(max_length=1024),
        ),
        migrations.DeleteModel(
            name="ModelStatus",
        ),
    ]
