{{/*
WOPR - Wargaming Oversight & Position Recognition
Copyright (c) 2025 Bob Bomar <bob@bomar.us>
SPDX-License-Identifier: MIT
*/}}

{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wopr-api.fullname" . }}
  labels:
    {{- include "wopr-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "wopr-api.api.selectorLabels" . | nindent 4 }}
{{- end }}
