# Generated by Django 5.1.15 on 2026-02-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="checksum",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="filename",
            field=models.CharField(db_index=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
