# Generated by Django 5.1.15 on 2026-02-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_image_checksum_image_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.image"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.session"
                    ),
                ),
            ],
            options={
                "db_table": "session_images",
                "ordering": ["session", "image"],
                "unique_together": {("session", "image")},
            },
        ),
    ]
