# Generated by Django 5.1.15 on 2026-02-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sessionimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="round",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="move",
            name="turn",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
