# Generated by Django 5.1.15 on 2026-02-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_move_round_remove_move_turn_round_turn_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="move",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="move",
            name="player",
        ),
        migrations.RemoveField(
            model_name="move",
            name="previous_move",
        ),
        migrations.RemoveField(
            model_name="move",
            name="session",
        ),
    ]
