# Generated by Django 5.1.15 on 2026-02-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_move_options_remove_move_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="player",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to="core.player"
            ),
            preserve_default=False,
        ),
    ]
