# Generated by Django 5.1.15 on 2026-02-06 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_move_player"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sessionplayer",
            unique_together={("session", "player")},
        ),
        migrations.AddField(
            model_name="move",
            name="turn",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="core.turn"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="turn",
            name="round",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="core.round"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sessionplayer",
            name="seat",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="move",
            unique_together={("turn", "player")},
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("session", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="sessionplayer",
            unique_together={("session", "player"), ("session", "seat")},
        ),
        migrations.AlterUniqueTogether(
            name="turn",
            unique_together={("session", "number")},
        ),
        migrations.DeleteModel(
            name="TurninRound",
        ),
    ]
