# Generated by Django 5.1.15 on 2026-02-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_sessionplayer_unique_together_move_turn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.game"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.image"
                    ),
                ),
            ],
            options={
                "db_table": "image_game",
                "ordering": ["game", "image"],
                "unique_together": {("game", "image")},
            },
        ),
    ]
