# Generated by Django 5.1.15 on 2026-02-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_imagegame"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameLabelproj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ls_project_id", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.game"
                    ),
                ),
            ],
            options={
                "db_table": "game_labelproj",
                "ordering": ["game", "ls_project_id"],
                "unique_together": {("game", "ls_project_id")},
            },
        ),
    ]
