# Generated by Django 5.1.15 on 2026-02-25 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_gamelabelproj"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="turn",
            unique_together={("round", "number")},
        ),
        migrations.CreateModel(
            name="MLDataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "short_id",
                    models.CharField(db_index=True, max_length=5, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.game"
                    ),
                ),
            ],
            options={
                "db_table": "ml_dataset",
                "ordering": ["-created_at"],
            },
        ),
    ]
