#!/usr/bin/env bash
# Copyright 2026 Bob Bomar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# scripts/generate-version.sh
# Generates version info from Git metadata
# Usage: ./scripts/generate-version.sh [output_file]

set -euo pipefail

OUTPUT_FILE="${1:-wopr-core/wopr/version.py}"

# Ensure we're in a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "ERROR: Not in a git repository" >&2
    exit 1
fi

# Get git metadata
GIT_COMMIT=$(git rev-parse HEAD)
GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_TAG=$(git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-${GIT_COMMIT_SHORT}")
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
BUILD_USER="${USER}@$(hostname)"

# Check if working tree is dirty
if [[ -n $(git status --porcelain) ]]; then
    GIT_DIRTY="True"
    GIT_TAG="${GIT_TAG}-dirty"
else
    GIT_DIRTY="False"
fi

# Create output directory if needed
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate the Python module
cat > "$OUTPUT_FILE" << EOF
#!/usr/bin/env python3
"""
WOPR Version Information
Auto-generated by scripts/generate-version.sh
DO NOT EDIT MANUALLY
"""

__version__ = "${GIT_TAG}"

GIT_COMMIT = "${GIT_COMMIT}"
GIT_COMMIT_SHORT = "${GIT_COMMIT_SHORT}"
GIT_BRANCH = "${GIT_BRANCH}"
GIT_TAG = "${GIT_TAG}"
GIT_DIRTY = ${GIT_DIRTY}
BUILD_DATE = "${BUILD_DATE}"
BUILD_USER = "${BUILD_USER}"


def version_info():
    """Return version information as a dictionary."""
    return {
        "version": __version__,
        "git_commit": GIT_COMMIT,
        "git_commit_short": GIT_COMMIT_SHORT,
        "git_branch": GIT_BRANCH,
        "git_tag": GIT_TAG,
        "git_dirty": GIT_DIRTY,
        "build_date": BUILD_DATE,
        "build_user": BUILD_USER,
    }


def version_string():
    """Return a formatted version string."""
    dirty = "-dirty" if GIT_DIRTY else ""
    return f"{__version__} ({GIT_COMMIT_SHORT}{dirty}) built {BUILD_DATE}"


if __name__ == "__main__":
    import json
    print(json.dumps(version_info(), indent=2))
EOF

chmod +x "$OUTPUT_FILE"

echo "Generated version info:"
echo "  File: $OUTPUT_FILE"
echo "  Version: $GIT_TAG"
echo "  Commit: $GIT_COMMIT_SHORT"
echo "  Branch: $GIT_BRANCH"
echo "  Dirty: $GIT_DIRTY"
echo "  Built: $BUILD_DATE"
