services:
  trainer:
    volumes:
      - /remote/wopr/models/ua/weights:/ultralytics/weights
      - /remote/wopr/models/ua/runs:/ultralytics/runs
      - /remote/wopr/models/ua/datasets:/ultralytics/datasets