services:
  trainer:
    tty: true
    stdin_open: true
    shm_size: '4gb'
    runtime: nvidia
    build:
      context: container/
      dockerfile: Dockerfile
    volumes:
      - /remote/wopr/models/ua/weights:/ultralytics/weights
      - /remote/wopr/models/ua/runs:/ultralytics/runs
      - /remote/wopr/models/ua/datasets:/ultralytics/datasets