[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wopr-cam"
version = "0.2.0"
description = "WOPR - Camera System"
authors = [{ name = "Bob Bomar", email = "bob@bomar.us" }]
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "picamera2",
]

[project.optional-dependencies]
dev = [
  "black",
  "django-stubs",
  "ipdb",
  "pip-tools",
  "ruff",
  "pytest",
  ]
