{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.postgresql.external.password | quote }}
  APP_KEYS: {{ .Values.strapi.appKeys | quote }}
  API_TOKEN_SALT: {{ .Values.strapi.apiTokenSalt | quote }}
  ADMIN_JWT_SECRET: {{ .Values.strapi.adminJwtSecret | quote }}
  JWT_SECRET: {{ .Values.strapi.jwtSecret | quote }}
  TRANSFER_TOKEN_SALT: {{ .Values.strapi.transferTokenSalt | quote }}
{{- end }}
