apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "80.4.1"

dependencies:
  - name: kube-prometheus-stack
    version: 80.4.1
    repository: "https://prometheus-community.github.io/helm-charts"

  - name: loki
    version: 6.48.0
    repository: "https://grafana.github.io/helm-charts"

  - name: tempo
    version: 1.24.1
    repository: "https://grafana.github.io/helm-charts"