services:
  trainer_simple_mk1:
    image: ultralytics/ultralytics:latest
    container_name: trainer_simple_mk1
    volumes:
      - /remote/wopr/models/ua/weights:/ultralytics/weights
      - /remote/wopr/models/ua/runs:/ultralytics/runs
      - /remote/wopr/models/ua/datasets:/ultralytics/datasets
      - /remote/wopr/models/ua/weights:/remote/wopr/models/ua/weights
      - /remote/wopr/models/ua/runs:/remote/wopr/models/ua/runs
      - /remote/wopr/models/ua/datasets:/remote/wopr/models/ua/datasets
    shm_size: '4gb'
    runtime: nvidia
    command: 
      - yolo 
      - train
      - "model=${MODEL:-yolo11n.pt}"
      - "data=${DATASET}"
      - "project=${RUNS:-/ultralytics/runs}"
      - "imgsz=1280"
      - "epochs=35"
      - "patience=20"
      - "batch=8"
      - "augment=True"
    working_dir: /ultralytics
    stdin_open: true
    tty: true
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True