[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wopr-boh"
version = "0.1.5-beta"
description = "WOPR - Back of House"
authors = [{ name = "Bob Bomar", email = "bob@bomar.us" }]
dependencies = [
  "django",
  "gunicorn",
  "psycopg2-binary",
  "whitenoise",
]

[project.optional-dependencies]
dev = ["black",
  "django-stubs",
  "ipdb",
  "pip-tools",
  "ruff",
  "pytest"]
