
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ludpy"
version = "0.1.6-beta"
description = "Ludii Python Interface"
authors = [{ name = "Bob Bomar", email = "bob@bomar.us" }]
dependencies = [
    "jpype1"
]

[project.optional-dependencies]
dev = [
  "black",
  "django-stubs",
  "ipdb",
  "pip-tools",
  "ruff",
  "pytest",
  ]
