wopr-baseapp:
  app:
    name: wopr-web
  replicaCount: 1

  image:
    registry: ghcr.io
    repository: travismontana/wopr/wopr-web
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    className: wopr-traefik
    hosts:
      - host: wopr.tailandtraillabs.org
        paths:
          - path: /
            pathType: Prefix
    tls: 
      - secretName: wopr-web-tls
        hosts:
          - wopr.tailandtraillabs.org
  volumeMounts:
    - name: config
      mountPath: /config
    - name: wopr-data
      mountPath: /remote/wopr
  volumes:
    - name: config
      configMap:
        name: wopr-json
    - name: wopr-data
      persistentVolumeClaim:
        claimName: wopr-web-nfs-pvc
  env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: wopr-db-cluster-app
          key: host
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: wopr-db-cluster-app
          key: port
    - name: DB_DATABASE
      valueFrom:
        configMapKeyRef:
          name: wopr-config
          key: WOPR_METADATA_DB
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: wopr-db-user-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wopr-db-user-credentials
          key: password
    - name: LABEL_STUDIO_TOKEN
      valueFrom:
        secretKeyRef:
          name: labelstudio-token-secret
          key: labelstudio-token
