"""
Django settings for back_of_house project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from ipaddress import ip_address, ip_network


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-d-mku7ye=8i3nigjh$a474lr1huy#^1=1sq85(8m3^=i+blsd3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["bob.geocities.com", "localhost", "127.0.0.1", "10.42.0.242"]


# Application definition

INSTALLED_APPS = [
    "core.apps.CoreConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "back_of_house.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "models/templates",
            BASE_DIR / "game_sessions/templates",
            BASE_DIR / "training/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "back_of_house.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_DATABASE"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static_files", BASE_DIR / "images"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

WHITENOISE_COMPRESSION = True
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0


class CIDRAwareAllowedHosts(list):
    """ALLOWED_HOSTS that supports CIDR notation"""

    def __init__(self, hosts, cidrs=None):
        super().__init__(hosts)
        self.cidrs = [ip_network(cidr) for cidr in (cidrs or [])]

    def __contains__(self, host):
        # Check standard host list first
        if super().__contains__(host) or super().__contains__("*"):
            return True

        # Strip port if present
        host_only = host.split(":")[0]

        # Check CIDR ranges
        try:
            host_ip = ip_address(host_only)
            for network in self.cidrs:
                if host_ip in network:
                    return True
        except ValueError:
            # Not an IP address, doesn't match CIDR
            pass

        return False


# Configuration
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = CIDRAwareAllowedHosts(
        hosts=[
            "bob.geocities.com",
            "localhost",
            "127.0.0.1",
            "boh.wopr.tailandtraillabs.org",
            ".svc.cluster.local",  # k8s service mesh
        ],
        cidrs=[
            "10.42.0.0/16",  # k3s pod network
            "10.43.0.0/16",  # k3s service network (if needed)
        ],
    )

CSRF_TRUSTED_ORIGINS = [
    "https://boh.wopr.tailandtraillabs.org",
    "https://bob.geocities.com",
]
