[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wopr-model"
version = "0.1.5-beta"
description = "WOPR - Model Control"
authors = [{ name = "Bob Bomar", email = "bob@bomar.us" }]
dependencies = [
  "requests",
  "fastapi~=0.115.6",
  "uvicorn[standard]~=0.34.0",
  "PyYAML~=6.0.2",
  "httpx",
  "attrs",
  "python-dateutil",
  "requests",
  "ultralytics-opencv-headless",
  "opencv-python-headless",
]

[project.optional-dependencies]
dev = [
  "black",
  "django-stubs",
  "ipdb",
  "pip-tools",
  "ruff",
  "pytest",
  ]
