apiVersion: v1
kind: Secret
metadata:
  name: wopr-db-user-credentials
  namespace: wopr
type: kubernetes.io/basic-auth
stringData:
  username: wopr-db-user
  password: <generate-something-secure>
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: wopr-db
  namespace: wopr
spec:
  cluster:
    name: wopr-config-db-cluster
  name: wopr-db-user
  owner: wopr-db-user
