# Generated by Django 5.1.15 on 2026-01-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelfamily",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
