# Generated by Django 5.1.15 on 2026-01-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_modelfamily_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelfamily",
            name="mf_status",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
