apiVersion: v1
kind: Service
metadata:
  name: {{ include "wopr-api.fullname" . }}
  labels:
    {{- include "wopr-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "wopr-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
